In [156]:
import numpy as np
import pandas as pd
from os import walk
import os
#from google.colab import drive

from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

import matplotlib.pyplot as plt

#NLP stuff
import string
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.porter import *

# sklearn stuff
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer

In [157]:
# read the speeches data from the csv (change the path so that it works for you)
df = pd.read_csv('raw_data.csv').set_index(['Year', 'ISO-alpha3 Code'])

# create a subset (this step can be skipped by putting a # in front of it)
df = df.loc[2005:]

In [158]:
# create a count vectorizer that 
vectorizer = CountVectorizer(stop_words = ['english'], max_features = 1000)

# fit the speech data and transform it into a sparse matrix
X = vectorizer.fit_transform(subset['Speech'].to_numpy())

In [159]:
# create a dataframe using the dense count matrix, index of the original speeches data and the features from the vectorizer
count_vect_df = pd.DataFrame(X.todense(), index=df.index, columns=vectorizer.get_feature_names())

In [160]:
count_vect_df

                      000  10  11  15  19  20  2005  2015  2030  30  ...  \
Year ISO-alpha3 Code                                                 ...
2005 AFG                1   0   0   0   0   0     3     0     0   0  ...
     AGO                0   0   0   0   0   0     1     0     0   0  ...
     ALB                1   0   0   0   0   0     2     0     0   0  ...
     AND                0   0   0   0   0   0     0     0     0   0  ...
     ARE                0   0   0   0   0   0     0     0     0   0  ...
...                   ...  ..  ..  ..  ..  ..   ...   ...   ...  ..  ...
2020 WSM                0   0   0   1   6   0     0     0     2   0  ...
     YEM                0   0   0   0   0   0     0     0     0   0  ...
     ZAF                0   0   0   0   4   0     0     0     0   0  ...
     ZMB                0   0   0   0   4   0     0     1     1   0  ...
     ZWE                0   0   0   1   5   0     0     0     1   0  ...

                      world  would  year  years  yemen  yet  you  young  your  \
Year ISO-alpha3 Code
2005 AFG                  1      2     3      4      0    1    0      0     0
     AGO                  5      3     0      2      0    0    0      0     0
     ALB                  6      4     2      3      0    1    0      0     0
     AND                  7      1     0      3      0    0    0      0     0
     ARE                  4      0     0      0      0    0    1      0     1
...                     ...    ...   ...    ...    ...  ...  ...    ...   ...
2020 WSM                  9      2     4      3      0    1    0      1     0
     YEM                  1      4     1      1      9    0    2      0     2
     ZAF                 10      0     3      2      0    0    0      1     1
     ZMB                  4      1     0      0      0    0    1      3     3
     ZWE                 10      0     4      1      0    0    3      0    10

                      youth
Year ISO-alpha3 Code
2005 AFG                  0
     AGO                  0
     ALB                  0
     AND                  0
     ARE                  0
...                     ...
2020 WSM                  1
     YEM                  0
     ZAF                  0
     ZMB                  2
     ZWE                  0

[3086 rows x 1000 columns]